In [5]:
import pandas as pd
import statsmodels.api as sm
df = pd.read_csv("dataset/train.csv", sep=',', parse_dates=[2])

df.head(10)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
5,6,5,2015-07-31,5651,589,1,1,0,1
6,7,5,2015-07-31,15344,1414,1,1,0,1
7,8,5,2015-07-31,8492,833,1,1,0,1
8,9,5,2015-07-31,8565,687,1,1,0,1
9,10,5,2015-07-31,7185,681,1,1,0,1

In [6]:
df.corr()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday
Store,1.000000,-0.000008,0.005126,0.024325,-0.000047,0.000058,0.000641
DayOfWeek,-0.000008,1.000000,-0.462125,-0.386445,-0.528963,-0.392925,-0.205388
Sales,0.005126,-0.462125,1.000000,0.894711,0.678472,0.452345,0.085124
Customers,0.024325,-0.386445,0.894711,1.000000,0.616768,0.316169,0.071568
Open,-0.000047,-0.528963,0.678472,0.616768,1.000000,0.295042,0.086171
Promo,0.000058,-0.392925,0.452345,0.316169,0.295042,1.000000,0.067483
SchoolHoliday,0.000641,-0.205388,0.085124,0.071568,0.086171,0.067483,1.000000

In [7]:
# LR input
featureColumns = ['Promo', 'Open', 'DayOfWeek', 'SchoolHoliday']
targetColumn = 'Sales'

inputData = pd.DataFrame(df, columns=featureColumns)
inputData = sm.add_constant(inputData, has_constant='add')
targetData = pd.DataFrame(df, columns=[targetColumn])

# Run LR
model = sm.OLS(targetData, inputData).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.532
Model:                            OLS   Adj. R-squared:                  0.532
Method:                 Least Squares   F-statistic:                 2.893e+05
Date:                Mon, 21 May 2018   Prob (F-statistic):               0.00
Time:                        23:17:11   Log-Likelihood:            -9.4549e+06
No. Observations:             1017209   AIC:                         1.891e+07
Df Residuals:                 1017204   BIC:                         1.891e+07
Df Model:                           4
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           540.8006     12.395     43.632      0.000     516.507     565.094
Promo          2071.7724      5.882    352.214      0.000    2060.244    2083.301
Open           5855.8783      8.247    710.101      0.000    5839.715    5872.041
DayOfWeek      -107.6904      1.639    -65.722      0.000    -110.902    -104.479
SchoolHoliday    68.2146      6.967      9.791      0.000      54.559      81.870
==============================================================================
Omnibus:                   436352.678   Durbin-Watson:                   1.721
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          3217630.605
Skew:                           1.908   Prob(JB):                         0.00
Kurtosis:                      10.833   Cond. No.                         25.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""